spring:
  cloud:
    stream:
      bindings:
        output:
          producer:
            useNativeEncoding: true
    kafka:
      binder:
        configuration:
          value:
            serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  kafka:
    producer:
      properties:
        schema:
          registry:
            url: http://localhost:8081
